version: "3.5"

services:
  db_auth: 
    container_name: db_api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=green12api
      - POSTGRES_USER=admin
    image: postgres:15.5-alpine3.18
    # volumes:
    #   - C:/Users/Bob/VS Project/GreenBit_v.0.2/Data Base/dump.sql:/docker-entrypoint-initdb.d/dump.sql
